### ISSUE TITLE
Not working with ESLint 9

### ISSUE THREAD

**Issue by JonathanMSifleet** [mansona/lint-to-the-future#38]
When running `npx lint-to-the-future ignore` I get the following error: 

```
/proj-directory/node_modules/lint-to-the-future-eslint/index.js:54
    cli = new CLIEngine();
          ^

TypeError: CLIEngine is not a constructor
    at Object.ignoreAll (/proj-directory/node_modules/lint-to-the-future-eslint/index.js:54:11)
    at Command.<anonymous> (/proj-directory/node_modules/lint-to-the-future/cli.js:159:27)

Node.js v18.19.1
```

**Comment by mansona** [comment]
Fixed in lint-to-the-future-eslint@2.2.0
